Small fixes
instagram4j/instagram4j pull request #586
Opened 2021-05-11 19:40 UTC by gzsombor

This PR contains small fixes:
* Treating similar structures is sometimes helpful - you don't need to repeat the code which deals with ReelImageMedia and TimelineImageMedia, or the VideoVersionsMeta and ImageVersionsMeta. 
* fixing the 'caraousel' typo

2021-05-15 23:24 UTC, dcmdeivid approved these changes

2021-05-25 22:47 UTC, jvogit commented
Hi sorry there was been no activity on this PR. Providing a little update:

I will get to it when I have the time and after I fix the release pipeline (we used bintray before but that has now been sunsetted)

2021-06-13 02:58 UTC, jvogit requested changes
I like the idea of using interfaces, so similar views can be grouped all into one with the same functions and such (Such as all ImageMedias). I think it would be very convenient with further abstractions. 

I believe the changes look good. I would like to see ImageMedia be used on ThreadImageMedia, ImageCarouselItem, etc. just to be more complete and perhaps also a VideoMedia option too!

If you want you can add more abstractions in this PR or a separate PR. The only changes I suggest is probably the name of Rectangle -> Meta and abstracting the ThreadImageMedia and CarouselImageMedia.

Anyways, sorry for the long delay. Thanks for contributing!

2021-06-13 02:58 UTC, jvogit commented on src/main/java/com/github/instagram4j/instagram4j/models/media/Rectangle.java
> +public interface Rectangle {
I think Meta instead of rectangle may be a more fitting name since it used for the Image/Video Meta.

2021-06-13 20:33 UTC, gzsombor commented
I've changed Rectangle to Meta, however, I couldn't add ImageMedia interface to ThreadImageMedia, neither to ImageCarouselItem, because both lacks a couple of methods, like _getCaption,getCode,getDevice_timestamp,getFilter_type,getId,getPk,getTaken_at,getUser_.

2021-06-15 07:22 UTC, jvogit approved these changes
lgtm. Thanks for contributing

2021-06-15 07:22 UTC, merged